/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Multicall2__factory } from "./factories/Multicall2__factory";
export type { Multicall2 } from "./Multicall2";
